### ISSUE TITLE
The macro 'plugin.dependencies' is unknown

### ISSUE THREAD

**Issue by nmwael** [bsorrentino/maven-confluence-plugin#129]
Im currently trying to use the plugin and running it as bare bone as possible. Im getting the following exception (all files are named properly without .tx):
[confluence.plugin.txt](https://github.com/bsorrentino/maven-confluence-plugin/files/492582/confluence.plugin.txt)

[pom.xml.txt](https://github.com/bsorrentino/maven-confluence-plugin/files/492588/pom.xml.txt)

[template.confluence.txt](https://github.com/bsorrentino/maven-confluence-plugin/files/492590/template.confluence.txt)

**Comment by bsorrentino** [comment]
Hi

I've seen your log and looks weird,  I need further detail:  **Are you generating documentation for a maven plugin  ?**

**Comment by bsorrentino** [comment]
I've duplicated the issue in my environment

The problem is that the  **`defaultTemplate.confluence`** embedded in **`confluence-reporting-maven-plugin-5.0-SNAPSHOT.jar!/defaultTemplate.confluence`** will, erroneously, contain the removed `plugin.dependencies` macro  

I've deployed the fix in version `5.0-SNAPSHOT` please test it and let me know.

>**However in your case there is another issue to take in consideration.
The template that you provide cannot be found from plugin then the plugin uses the default one that contains the unknown macro.**

> **Where are you put your template ?**

**Comment by bsorrentino** [comment]
fix release with `5.0`
