### ISSUE TITLE
Documentation update request: how to obtain credentials for Conf cloud after it's moved to Openapi and API keys

### ISSUE THREAD

**Issue by oxygenecore** [bsorrentino/maven-confluence-plugin#218]
I can not set up the plugin - I stuck in the step when I have to define credentials. I can not find information on how can I get credentials (username / password) if the cloud version is bound to Google openapi, and all the documentation I can find talks about API keys. Could this info be included into official documentation for the plugin?

**Comment by bsorrentino** [comment]
hi @oxygenecore 

I never dealt with such use case so you won't find any documentation about it.

I'll take a look about to try to implement such feature. In the meanwhile will be very appreciate if you could share me any documentation that could help me

**Comment by bsorrentino** [comment]
hi @oxygenecore  

I've taken a view to official atlassian documentation about REST Api and I found out the following page  [Basic auth for REST APIs](https://developer.atlassian.com/cloud/jira/platform/basic-auth-for-rest-apis/) that states that it is enough to obtain an `Api token` and pass it instead of `password`.

What do you think? Could you test it and let me know?

Thanks in advance

**Comment by oxygenecore** [comment]
@bsorrentino thank you for taking look into it before I did, and for the explanation. I've switched to other tasks now, will comment here once I get back and test it. Thank you =)

**Comment by oxygenecore** [comment]
@bsorrentino thank you, we were able to connect to Confluence instance from Maven.
