### ISSUE TITLE
[WARNING] Plugin without mojos.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bsorrentino/maven-confluence-plugin#33]
```
I am able to generate output for the confluence-summary report, but I don't get 
any output for the plugin-confluence-summary report.  I notice that there are 
warnings in the log regarding no mojo's found, but I am not sure what the real 
issue is.

I have attached the output from maven.  I am running on Ubuntu 11.10, Sun JDK 
1.6.x, and maven 3.x.

Let me know what else you might need to help troubleshoot this issue.

thanks,
Garrett

```

Original issue reported on code.google.com by `garretts...@gmail.com` on 6 Jan 2012 at 1:41

Attachments:
- [site.out](https://storage.googleapis.com/google-code-attachments/maven-confluence-plugin/issue-33/comment-0/site.out)

**Comment by GregDomjan** [comment]
Having a similar issue 

> [INFO] --- confluence-reporting-maven-plugin:4.6:deploy (default-cli) @ x-maven-plugin ---
> [INFO] executeReport isSnapshot = [true] isRemoveSnapshots = [false]
> Site
>  Page: my-site-generation-test - jar:file:/c:/Data/.m2/repository-m3/org/bsc/maven/confluence-reporting-maven-plugin/4.6/confluence-reporting-maven-plugin-4.6.jar!/defaultTemplate.confluence
> [WARNING] Plugin without mojos. No mojo definitions were found for plugin: com.y:x-maven-plugin.
> MojoScanner:class org.apache.maven.tools.plugin.scanner.DefaultMojoScanner

With Maven 3.3.3  and 
confluence-reporting-maven-plugin:4.6  as a build plugin
site:3.4 
maven-plugin-plugin:3.4

running from command line   mvn confluence-reporting:deploy
after mvn clean package site

Initially I thought it was due to using maven2 style comment annotations, so updated to java1.5 style annotations which didn't help.
